import config from './config/environment';
import AddonDocsRouter, { docsRoute } from 'ember-cli-addon-docs/router';

const Router = AddonDocsRouter.extend({
  location: config.locationType,
  rootURL: config.rootURL
});

Router.map(function() {
  this.route('example')
  docsRoute(this, function() {
    this.route('forms'); // docs subpage
    this.route('extras');
    this.route('cards');
    this.route('providers');
    this.route('api', function () { // autogenerated API homepage (required)
      this.route('item', { path: '/*path' }); // autogenerated API subpages (required)
    });
  });

  this.route('not-found', { path: '/404' });

});

export default Router;
